In [8]:
import numpy as np
#created for array and matrix manipulation

In [3]:
l=[1,2,3,4,5]

In [9]:
arr=np.array(l)
#list to array conv

In [10]:
arr

array([1, 2, 3, 4, 5])

In [12]:
type(arr)
#n dimensional array

numpy.ndarray

In [13]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [15]:
arr1=np.array([[1,2,3],[3,4,5]])

In [18]:
arr.ndim
#checks dimension of array

1

In [19]:
arr1.ndim

2

In [22]:
arr1
#rows are X axis (index: 0 and 1)...columns are Y axis (index:0,1,2)
#(X,Y)-->(0,0)=1,(0,1)=2,(0,2)=3,(1,0)=3,(1,1)=4,(1,2)=5

array([[1, 2, 3],
       [3, 4, 5]])

In [29]:
mat=np.matrix(l)
#matrix always have 2 dim...array has 1 dim
#matrix is one type of array only...say like collection of array

In [26]:
mat

matrix([[1, 2, 3, 4, 5]])

In [31]:
np.asanyarray(l)
#l was a list hence, asanyarray converted list to array

array([1, 2, 3, 4, 5])

In [30]:
np.asanyarray(mat)
#if something is already in any form of array, asanyarray will not make changes
#here mat is a matrix which is kind of an array only

matrix([[1, 2, 3, 4, 5]])

In [32]:
arr

array([1, 2, 3, 4, 5])

In [33]:
a=arr

In [34]:
a

array([1, 2, 3, 4, 5])

In [35]:
arr[0]=100

In [36]:
arr

array([100,   2,   3,   4,   5])

In [37]:
a

array([100,   2,   3,   4,   5])

In [43]:
b=np.copy(arr)
#np.copy creates a new memory location unlike normal assignment operation
#this is deep copy

In [39]:
b

array([100,   2,   3,   4,   5])

In [40]:
arr[1]=700

In [41]:
arr

array([100, 700,   3,   4,   5])

In [42]:
b

array([100,   2,   3,   4,   5])

In [45]:
np.fromfunction(lambda i,j : i==j, (3,3))
#True only in (0,0),(1,1) and (2,2) places

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [46]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [48]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [49]:
iterable=(i*i for i in range(5))

In [50]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [51]:
np.fromstring('23 45 56',sep=" ")

array([23., 45., 56.])

In [52]:
np.fromstring('23,45,56',sep=",")

array([23., 45., 56.])

In [53]:
arr1

array([[1, 2, 3],
       [3, 4, 5]])

In [54]:
arr.ndim

1

In [55]:
arr1.ndim

2

In [58]:
arr.size
#returns total no of elements

5

In [59]:
arr1.size

6

In [60]:
arr.shape

(5,)

In [61]:
arr1.shape

(2, 3)

In [62]:
arr.dtype

dtype('int64')

In [63]:
arr1.dtype

dtype('int64')