In [1]:
import numpy as np

In [2]:
##Sort , Search and Count Functions

In [5]:
arr=np.array([4,2,8,5,9,56,12])

In [6]:
arr

array([ 4,  2,  8,  5,  9, 56, 12])

In [7]:
np.sort(arr)

array([ 2,  4,  5,  8,  9, 12, 56])

In [9]:
np.searchsorted(arr,6)

4

In [10]:
arr1=np.array([0,324,645,65,6,6,0,0,0,234])

In [11]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [12]:
np.count_nonzero(arr1)

6

In [14]:
np.where(arr1>0)
#gives indexes

(array([1, 2, 3, 4, 5, 9]),)

In [15]:
np.extract(arr1>2,arr1)

array([324, 645,  65,   6,   6, 234])

In [16]:
#Numpy - Byte Swapping

In [18]:
arr

array([ 4,  2,  8,  5,  9, 56, 12])

In [20]:
arr.byteswap()
#swaps original data with its byte representation

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  648518346341351424, 4035225266123964416,
        864691128455135232])

In [21]:
arr

array([ 4,  2,  8,  5,  9, 56, 12])

In [22]:
arr.byteswap(True)

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  648518346341351424, 4035225266123964416,
        864691128455135232])

In [23]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  648518346341351424, 4035225266123964416,
        864691128455135232])

In [24]:
#Numpy - Copies & Views

In [25]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [28]:
a=np.copy(arr1)
#deep copy

In [34]:
b=arr1.view()
#shallow copy

In [30]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [31]:
b[0]=176

In [32]:
b

array([176, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [33]:
arr1

array([176, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [35]:
#Numpy - Matrix Library

In [36]:
import numpy.matlib as nm

In [37]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [38]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [40]:
#Numpy - Linear Algebra

In [43]:
arr1=np.random.randint([[2,3], [4,5]])

In [45]:
arr2=np.random.randint([[5,3], [2,5]])

In [46]:
arr1

array([[1, 2],
       [1, 0]])

In [49]:
arr2

array([[0, 2],
       [1, 1]])

In [50]:
np.dot(arr1,arr2)

array([[2, 4],
       [0, 2]])

In [51]:
arr1@arr2

array([[2, 4],
       [0, 2]])