In [1]:
import numpy as np

In [2]:
range(5)

range(0, 5)

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
np.arange(0.4,10.4,0.5)

array([0.4, 0.9, 1.4, 1.9, 2.4, 2.9, 3.4, 3.9, 4.4, 4.9, 5.4, 5.9, 6.4,
       6.9, 7.4, 7.9, 8.4, 8.9, 9.4, 9.9])

In [7]:
list(np.arange(0.4,10.6,0.3))

[0.4,
 0.7,
 0.9999999999999999,
 1.2999999999999998,
 1.5999999999999996,
 1.8999999999999995,
 2.1999999999999997,
 2.4999999999999996,
 2.7999999999999994,
 3.099999999999999,
 3.399999999999999,
 3.6999999999999993,
 3.999999999999999,
 4.299999999999999,
 4.6,
 4.8999999999999995,
 5.199999999999999,
 5.499999999999999,
 5.799999999999999,
 6.099999999999999,
 6.399999999999999,
 6.699999999999999,
 6.999999999999999,
 7.299999999999999,
 7.599999999999999,
 7.899999999999999,
 8.199999999999998,
 8.499999999999998,
 8.799999999999999,
 9.099999999999998,
 9.399999999999999,
 9.699999999999998,
 9.999999999999998,
 10.299999999999999]

In [8]:
np.linspace(1,5,20)
#divides 1 to 5 range equally in 20 numbers

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [9]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.zeros((3,3,4))
#creates 3 3X4 matrixes
#3D data, on Z axis 3 matrixes are stacked on top of each other

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [2]:
arr=np.zeros((3,4,2,3))
#4, 2X3 matrixes in a set and then 3 stacks of 4, 2x3 matrixes 

In [14]:
arr.ndim
#4D so can't visualize

4

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
arr2=np.ones((3,4))

In [4]:
arr1=np.ones((2,3,4))

In [21]:
arr1.ndim

3

In [24]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
arr2+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [5]:
arr2*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [7]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [8]:
arr3=np.eye(5)
# 5x5 identity matrix

In [9]:
import pandas as pd

In [10]:
pd.DataFrame(arr3)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [11]:
np.random.rand(2,3)
#purely random

array([[0.24963782, 0.6939656 , 0.09153466],
       [0.20965702, 0.57501214, 0.8571841 ]])

In [12]:
np.random.randn(2,3)
#generates a normally distributed dataset..mean=0...std=1
#helpful in statistics class

array([[ 0.10603455,  1.27286744, -1.18988425],
       [ 0.55384333,  0.48929455,  1.24531426]])

In [13]:
arr5=np.random.randint(1,5, (3,4))
# 3x4 matrix with dataset in range of 1 to 5

In [14]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
arr5

array([[3, 1, 4, 2],
       [3, 4, 2, 4],
       [2, 3, 1, 1]])

In [24]:
arr5.size

12

In [25]:
arr5.shape

(3, 4)

In [15]:
arr5.reshape(2,6)

array([[2, 2, 2, 3, 4, 2],
       [2, 1, 3, 4, 4, 1]])

In [16]:
arr5

array([[2, 2, 2, 3],
       [4, 2, 2, 1],
       [3, 4, 4, 1]])

In [17]:
arr5.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [18]:
arr5.reshape(4,-1)

array([[2, 2, 2],
       [3, 4, 2],
       [2, 1, 3],
       [4, 4, 1]])

In [19]:
arr5.reshape(2,3,2,1,1,1)

array([[[[[[2]]],


         [[[2]]]],



        [[[[2]]],


         [[[3]]]],



        [[[[4]]],


         [[[2]]]]],




       [[[[[2]]],


         [[[1]]]],



        [[[[3]]],


         [[[4]]]],



        [[[[4]]],


         [[[1]]]]]])

In [20]:
arr6=np.random.randint(1,10,(5,6))
# 5x6 mat with data from 1 to 10

In [21]:
arr6

array([[1, 2, 8, 3, 8, 9],
       [9, 6, 3, 8, 4, 6],
       [1, 8, 2, 5, 4, 8],
       [3, 8, 2, 9, 3, 3],
       [8, 9, 8, 9, 1, 5]])

In [22]:
arr6>8

array([[False, False, False, False, False,  True],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False,  True, False,  True, False, False]])

In [23]:
arr6[arr6>8]

array([9, 9, 9, 9, 9])

In [24]:
arr6[0]

array([1, 2, 8, 3, 8, 9])

In [25]:
arr6[0,[0,1]]

array([1, 2])

In [26]:
arr6[2:4,[2,3]]

array([[2, 5],
       [2, 9]])

In [29]:
arr7=np.random.randint(1,3, (3,3))
arr8=np.random.randint(1,3, (3,3))

In [30]:
arr7

array([[2, 1, 1],
       [1, 2, 1],
       [2, 2, 2]])

In [31]:
arr8

array([[2, 1, 1],
       [2, 2, 1],
       [1, 1, 2]])

In [32]:
arr7+arr8

array([[4, 2, 2],
       [3, 4, 2],
       [3, 3, 4]])

In [33]:
arr7-arr8

array([[ 0,  0,  0],
       [-1,  0,  0],
       [ 1,  1,  0]])

In [37]:
arr7*arr8
#index wise multiplication

array([[4, 1, 1],
       [2, 4, 1],
       [2, 2, 4]])

In [36]:
#matrix multiplication

In [40]:
arr7@arr8
#matrix multiplication

array([[ 7,  5,  5],
       [ 7,  6,  5],
       [10,  8,  8]])

In [41]:
arr7/arr8
#index wise division

array([[1. , 1. , 1. ],
       [0.5, 1. , 1. ],
       [2. , 2. , 1. ]])

In [42]:
arr7/0

/tmp/ipykernel_77/3671141249.py:1: RuntimeWarning: divide by zero encountered in divide
  arr7/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [43]:
#Numpy - Broadcasting

In [61]:
arr=np.zeros((3,4))

In [62]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
arr+5
#broadcasting 5...this 5 has been broadcasted in arr

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [48]:
a=np.array([1,2,3,4])

In [49]:
a

array([1, 2, 3, 4])

In [63]:
arr+a
#a will be added columnwise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [74]:
b=np.array([[3,4,5]])

In [75]:
arr+b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [76]:
arr1=arr.T

In [77]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
arr3=arr1+b

In [79]:
arr+b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [81]:
np.sqrt(arr3)

array([[1.73205081, 2.        , 2.23606798],
       [1.73205081, 2.        , 2.23606798],
       [1.73205081, 2.        , 2.23606798],
       [1.73205081, 2.        , 2.23606798]])

In [82]:
np.log10(arr3)

array([[0.47712125, 0.60205999, 0.69897   ],
       [0.47712125, 0.60205999, 0.69897   ],
       [0.47712125, 0.60205999, 0.69897   ],
       [0.47712125, 0.60205999, 0.69897   ]])

In [83]:
np.exp(arr3)

array([[ 20.08553692,  54.59815003, 148.4131591 ],
       [ 20.08553692,  54.59815003, 148.4131591 ],
       [ 20.08553692,  54.59815003, 148.4131591 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [84]:
np.min(arr3)

3.0

In [85]:
np.max(arr3)

5.0