In [1]:
import numpy as np

In [2]:
#Numpy - Array Manipulation

In [5]:
arr=np.random.randint(1,10, (4,4))

In [6]:
arr

array([[4, 1, 3, 1],
       [1, 8, 2, 6],
       [8, 4, 6, 4],
       [4, 2, 6, 5]])

In [7]:
arr.reshape(8,2)

array([[4, 1],
       [3, 1],
       [1, 8],
       [2, 6],
       [8, 4],
       [6, 4],
       [4, 2],
       [6, 5]])

In [8]:
arr.T

array([[4, 1, 8, 4],
       [1, 8, 4, 2],
       [3, 2, 6, 6],
       [1, 6, 4, 5]])

In [9]:
arr.flatten()

array([4, 1, 3, 1, 1, 8, 2, 6, 8, 4, 6, 4, 4, 2, 6, 5])

In [12]:
np.expand_dims(arr,axis=1)
#columnwise expanded

array([[[4, 1, 3, 1]],

       [[1, 8, 2, 6]],

       [[8, 4, 6, 4]],

       [[4, 2, 6, 5]]])

In [14]:
np.expand_dims(arr,axis=0)

array([[[4, 1, 3, 1],
        [1, 8, 2, 6],
        [8, 4, 6, 4],
        [4, 2, 6, 5]]])

In [16]:
data=np.array([[1],[2],[3]])

In [17]:
data

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(data)

array([1, 2, 3])

In [19]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [22]:
np.roll(data,2)
#each address incremented by +2...1(0)=1(2),2(1)=2(3=1),3(2)=3(4=2)

array([[2],
       [3],
       [1]])

In [23]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
#Numpy - Binary Operations

In [27]:
arr1=np.random.randint(1,10, (3,4))
arr2=np.random.randint(1,10, (3,4))

In [28]:
arr1

array([[1, 9, 7, 1],
       [6, 9, 6, 5],
       [3, 9, 2, 5]])

In [29]:
arr2

array([[6, 2, 7, 8],
       [2, 1, 2, 5],
       [2, 8, 5, 2]])

In [30]:
arr1+arr2

array([[ 7, 11, 14,  9],
       [ 8, 10,  8, 10],
       [ 5, 17,  7,  7]])

In [31]:
arr1*arr2

array([[ 6, 18, 49,  8],
       [12,  9, 12, 25],
       [ 6, 72, 10, 10]])

In [32]:
arr1/arr2

array([[0.16666667, 4.5       , 1.        , 0.125     ],
       [3.        , 9.        , 3.        , 1.        ],
       [1.5       , 1.125     , 0.4       , 2.5       ]])

In [36]:
arr1**arr2

array([[       1,       81,   823543,        1],
       [      36,        9,       36,     3125],
       [       9, 43046721,       32,       25]])

In [37]:
~arr1

array([[ -2, -10,  -8,  -2],
       [ -7, -10,  -7,  -6],
       [ -4, -10,  -3,  -6]])

In [38]:
arr1

array([[1, 9, 7, 1],
       [6, 9, 6, 5],
       [3, 9, 2, 5]])

In [39]:
arr1>arr2

array([[False,  True, False, False],
       [ True,  True,  True, False],
       [ True,  True, False,  True]])

In [40]:
#Numpy - String Functions

In [41]:
arr=np.array(['ijaj','ahmed'])

In [42]:
arr

array(['ijaj', 'ahmed'], dtype='<U5')

In [43]:
np.char.upper(arr)

array(['IJAJ', 'AHMED'], dtype='<U5')

In [44]:
np.char.capitalize(arr)

array(['Ijaj', 'Ahmed'], dtype='<U5')

In [45]:
np.char.title(arr)

array(['Ijaj', 'Ahmed'], dtype='<U5')

In [46]:
#Numpy - Mathematical Functions

In [47]:
arr1

array([[1, 9, 7, 1],
       [6, 9, 6, 5],
       [3, 9, 2, 5]])

In [48]:
np.sin(arr1)

array([[ 0.84147098,  0.41211849,  0.6569866 ,  0.84147098],
       [-0.2794155 ,  0.41211849, -0.2794155 , -0.95892427],
       [ 0.14112001,  0.41211849,  0.90929743, -0.95892427]])

In [49]:
np.cos(arr1)

array([[ 0.54030231, -0.91113026,  0.75390225,  0.54030231],
       [ 0.96017029, -0.91113026,  0.96017029,  0.28366219],
       [-0.9899925 , -0.91113026, -0.41614684,  0.28366219]])

In [50]:
np.tan(arr1)

array([[ 1.55740772, -0.45231566,  0.87144798,  1.55740772],
       [-0.29100619, -0.45231566, -0.29100619, -3.38051501],
       [-0.14254654, -0.45231566, -2.18503986, -3.38051501]])

In [51]:
np.log10(arr1)

array([[0.        , 0.95424251, 0.84509804, 0.        ],
       [0.77815125, 0.95424251, 0.77815125, 0.69897   ],
       [0.47712125, 0.95424251, 0.30103   , 0.69897   ]])

In [52]:
np.exp(arr1)

array([[2.71828183e+00, 8.10308393e+03, 1.09663316e+03, 2.71828183e+00],
       [4.03428793e+02, 8.10308393e+03, 4.03428793e+02, 1.48413159e+02],
       [2.00855369e+01, 8.10308393e+03, 7.38905610e+00, 1.48413159e+02]])

In [54]:
np.power(arr1,2)
#power of 2

array([[ 1, 81, 49,  1],
       [36, 81, 36, 25],
       [ 9, 81,  4, 25]])

In [55]:
np.mean(arr1)

5.25

In [56]:
np.median(arr1)

5.5

In [57]:
np.mode(arr1)

AttributeError: module 'numpy' has no attribute 'mode'

In [58]:
np.std(arr1)

2.8613807855648994

In [59]:
np.var(arr1)

8.1875

In [60]:
np.min(arr1)

1

In [61]:
np.max(arr1)

9

In [62]:
#Numpy - Arithmetic Operations

In [63]:
arr1

array([[1, 9, 7, 1],
       [6, 9, 6, 5],
       [3, 9, 2, 5]])

In [64]:
arr2

array([[6, 2, 7, 8],
       [2, 1, 2, 5],
       [2, 8, 5, 2]])

In [65]:
arr1-arr2

array([[-5,  7,  0, -7],
       [ 4,  8,  4,  0],
       [ 1,  1, -3,  3]])

In [66]:
np.subtract(arr1,arr2)

array([[-5,  7,  0, -7],
       [ 4,  8,  4,  0],
       [ 1,  1, -3,  3]])

In [67]:
np.multiply(arr1,arr2)

array([[ 6, 18, 49,  8],
       [12,  9, 12, 25],
       [ 6, 72, 10, 10]])

In [68]:
np.mod(arr1,arr2)

array([[1, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 2, 1]])

In [69]:
np.power(arr1,arr2)

array([[       1,       81,   823543,        1],
       [      36,        9,       36,     3125],
       [       9, 43046721,       32,       25]])

In [70]:
np.sqrt(arr2)

array([[2.44948974, 1.41421356, 2.64575131, 2.82842712],
       [1.41421356, 1.        , 1.41421356, 2.23606798],
       [1.41421356, 2.82842712, 2.23606798, 1.41421356]])

In [71]:
#Numpy - Statistical functions

In [72]:
arr1

array([[1, 9, 7, 1],
       [6, 9, 6, 5],
       [3, 9, 2, 5]])

In [73]:
np.mean(arr1)

5.25

In [74]:
np.std(arr1)

2.8613807855648994

In [75]:
np.median(arr1)

5.5